FROM ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest

COPY fix-permissions /bin/

RUN fix-permissions /app/uploads

ENV EMBEDDINGS_PROVIDER=openai \
    EMBEDDINGS_MODEL=embeddings \
    RAG_PORT=8080